export const IMAGES = {
    boy: require("./boy.png"),
    girl: require("./girl.png"),
    community: require("./community.png"),
    whowe: require("./whowe.png"),
    icon1: require("./icons/1.png"),
    icon2: require("./icons/2.png"),
    icon3: require("./icons/3.png"),
    icon4: require("./icons/4.png"),
    icon5: require("./icons/5.png"),
    icon6: require("./icons/6.png"),
    whatsapp: require("./whatsapp.png"),
    tca_1: require("./projects/tca-1.png"),
    proj2: require("./projects/proj2.png"),
    proj3: require("./projects/proj3.png"),
    proj4: require("./projects/proj4.png"),
    abid: require("./testimonials/abid.png"),
    ismail: require("./testimonials/ismail.png"),
    ourProjectsHero: require("./ourProjectsHero.png"),
}